"""Deterministic research-only equity factor definitions and contracts."""

from __future__ import annotations

from typing import Final


SCHEMA_VERSION: Final[str] = "1.0"
ALLOWED_USE: Final[tuple[str, ...]] = (
    "hypothesis_seed",
    "research_screening",
    "operator_explanation",
)
FORBIDDEN_USE: Final[tuple[str, ...]] = (
    "direct_trade_signal",
    "candidate_promotion",
    "capital_allocation",
)

FACTOR_ROWS: Final[tuple[dict[str, object], ...]] = (
    {
        "factor_id": "earnings_yield",
        "display_name": "Earnings Yield",
        "family": "valuation",
        "description": "Inverse P/E style valuation signal using trailing earnings.",
        "formula_kind": "ratio_inverse",
        "required_fields": ["market_cap", "net_income_ttm"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["fundamental_point_in_time", "currency_consistent"],
    },
    {
        "factor_id": "fcf_yield",
        "display_name": "Free Cash Flow Yield",
        "family": "valuation",
        "description": "Free cash flow relative to market capitalization.",
        "formula_kind": "ratio",
        "required_fields": ["market_cap", "free_cash_flow_ttm"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["fundamental_point_in_time", "cash_flow_statement_ready"],
    },
    {
        "factor_id": "book_to_market",
        "display_name": "Book to Market",
        "family": "valuation",
        "description": "Book equity divided by market capitalization.",
        "formula_kind": "ratio",
        "required_fields": ["book_value_equity", "market_cap"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["balance_sheet_ready", "fundamental_point_in_time"],
    },
    {
        "factor_id": "price_to_sales",
        "display_name": "Price to Sales",
        "family": "valuation",
        "description": "Market capitalization relative to trailing revenue.",
        "formula_kind": "ratio",
        "required_fields": ["market_cap", "revenue_ttm"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["income_statement_ready", "fundamental_point_in_time"],
    },
    {
        "factor_id": "enterprise_value_to_ebit",
        "display_name": "Enterprise Value to EBIT",
        "family": "valuation",
        "description": "Enterprise value relative to operating earnings.",
        "formula_kind": "ratio",
        "required_fields": ["enterprise_value", "ebit_ttm"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["enterprise_value_ready", "income_statement_ready"],
    },
    {
        "factor_id": "roic",
        "display_name": "Return on Invested Capital",
        "family": "quality",
        "description": "Operating return relative to invested capital.",
        "formula_kind": "ratio",
        "required_fields": ["nopat_ttm", "invested_capital"],
        "point_in_time_required": True,
        "restatement_risk": "high",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["capital_structure_ready", "fundamental_point_in_time"],
    },
    {
        "factor_id": "return_on_assets",
        "display_name": "Return on Assets",
        "family": "quality",
        "description": "Net income relative to total assets.",
        "formula_kind": "ratio",
        "required_fields": ["net_income_ttm", "total_assets"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["balance_sheet_ready", "income_statement_ready"],
    },
    {
        "factor_id": "gross_profitability",
        "display_name": "Gross Profitability",
        "family": "quality",
        "description": "Gross profit relative to total assets.",
        "formula_kind": "ratio",
        "required_fields": ["gross_profit_ttm", "total_assets"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["balance_sheet_ready", "income_statement_ready"],
    },
    {
        "factor_id": "piotroski_f_score",
        "display_name": "Piotroski F-Score",
        "family": "financial_health",
        "description": "Composite accounting quality and balance-sheet strength score.",
        "formula_kind": "composite_score",
        "required_fields": ["roa", "operating_cash_flow", "gross_margin", "asset_turnover", "leverage_ratio"],
        "point_in_time_required": True,
        "restatement_risk": "high",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["multi_period_fundamentals", "fundamental_point_in_time"],
    },
    {
        "factor_id": "altman_z_score",
        "display_name": "Altman Z-Score",
        "family": "risk_distress",
        "description": "Bankruptcy-risk style composite score.",
        "formula_kind": "composite_score",
        "required_fields": ["working_capital", "retained_earnings", "ebit_ttm", "market_cap", "total_assets", "total_liabilities"],
        "point_in_time_required": True,
        "restatement_risk": "high",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["balance_sheet_ready", "income_statement_ready"],
    },
    {
        "factor_id": "beneish_m_score",
        "display_name": "Beneish M-Score",
        "family": "accounting_red_flags",
        "description": "Fraud-risk style accounting diagnostic.",
        "formula_kind": "composite_score",
        "required_fields": ["days_sales_receivables", "gross_margin_index", "asset_quality_index", "sales_growth_index", "depreciation_index", "sgai", "leverage_index", "total_accruals_to_assets"],
        "point_in_time_required": True,
        "restatement_risk": "high",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["multi_period_fundamentals", "fundamental_point_in_time"],
    },
    {
        "factor_id": "montier_c_score",
        "display_name": "Montier C-Score",
        "family": "accounting_red_flags",
        "description": "Accounting conservatism risk composite.",
        "formula_kind": "composite_score",
        "required_fields": ["dsri", "gmi", "aqi", "sgi", "depi", "lvgi", "tata"],
        "point_in_time_required": True,
        "restatement_risk": "high",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["multi_period_fundamentals", "fundamental_point_in_time"],
    },
    {
        "factor_id": "debt_to_equity",
        "display_name": "Debt to Equity",
        "family": "financial_health",
        "description": "Total debt relative to book equity.",
        "formula_kind": "ratio",
        "required_fields": ["total_debt", "book_value_equity"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["balance_sheet_ready"],
    },
    {
        "factor_id": "net_debt_to_ebitda",
        "display_name": "Net Debt to EBITDA",
        "family": "financial_health",
        "description": "Leverage measure relative to operating cash earnings.",
        "formula_kind": "ratio",
        "required_fields": ["net_debt", "ebitda_ttm"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["balance_sheet_ready", "income_statement_ready"],
    },
    {
        "factor_id": "accruals_ratio",
        "display_name": "Accruals Ratio",
        "family": "accounting_red_flags",
        "description": "Cash-conversion quality proxy based on accrual intensity.",
        "formula_kind": "ratio",
        "required_fields": ["net_income_ttm", "operating_cash_flow_ttm", "average_total_assets"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["cash_flow_statement_ready", "multi_period_fundamentals"],
    },
    {
        "factor_id": "six_month_momentum",
        "display_name": "Six Month Momentum",
        "family": "momentum",
        "description": "Price appreciation over the trailing six months.",
        "formula_kind": "price_return",
        "required_fields": ["price_history_6m"],
        "point_in_time_required": False,
        "restatement_risk": "low",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_price_window_integrity",
        "quality_gate_requirements": ["price_history_complete"],
    },
    {
        "factor_id": "twelve_month_momentum",
        "display_name": "Twelve Month Momentum",
        "family": "momentum",
        "description": "Price appreciation over the trailing twelve months.",
        "formula_kind": "price_return",
        "required_fields": ["price_history_12m"],
        "point_in_time_required": False,
        "restatement_risk": "low",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_price_window_integrity",
        "quality_gate_requirements": ["price_history_complete"],
    },
    {
        "factor_id": "adjusted_slope",
        "display_name": "Adjusted Slope",
        "family": "momentum",
        "description": "Regression-slope momentum adjusted for volatility and fit quality.",
        "formula_kind": "regression_slope",
        "required_fields": ["price_history_12m", "volatility_12m"],
        "point_in_time_required": False,
        "restatement_risk": "low",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_price_window_integrity",
        "quality_gate_requirements": ["price_history_complete", "volatility_ready"],
    },
    {
        "factor_id": "shareholder_yield",
        "display_name": "Shareholder Yield",
        "family": "shareholder_yield",
        "description": "Composite of dividend, net buyback, and debt paydown yield.",
        "formula_kind": "composite_yield",
        "required_fields": ["dividends_paid_ttm", "net_buybacks_ttm", "net_debt_change_ttm", "market_cap"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["capital_returns_ready", "fundamental_point_in_time"],
    },
    {
        "factor_id": "dividend_yield",
        "display_name": "Dividend Yield",
        "family": "shareholder_yield",
        "description": "Dividends paid relative to market capitalization.",
        "formula_kind": "yield",
        "required_fields": ["dividends_paid_ttm", "market_cap"],
        "point_in_time_required": True,
        "restatement_risk": "low",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["capital_returns_ready"],
    },
    {
        "factor_id": "buyback_yield",
        "display_name": "Buyback Yield",
        "family": "shareholder_yield",
        "description": "Net share repurchases relative to market capitalization.",
        "formula_kind": "yield",
        "required_fields": ["net_buybacks_ttm", "market_cap"],
        "point_in_time_required": True,
        "restatement_risk": "medium",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_report_lag_governance",
        "quality_gate_requirements": ["capital_returns_ready", "shares_outstanding_ready"],
    },
    {
        "factor_id": "average_daily_value_traded",
        "display_name": "Average Daily Value Traded",
        "family": "liquidity",
        "description": "Liquidity proxy based on trailing traded value.",
        "formula_kind": "liquidity_proxy",
        "required_fields": ["average_daily_value_traded_90d"],
        "point_in_time_required": False,
        "restatement_risk": "low",
        "missing_value_policy": "block_factor",
        "lookahead_bias_risk": "requires_price_window_integrity",
        "quality_gate_requirements": ["price_history_complete", "volume_history_complete"],
    },
)


def _row_with_policy(row: dict[str, object]) -> dict[str, object]:
    return {
        **row,
        "allowed_use": list(ALLOWED_USE),
        "forbidden_use": list(FORBIDDEN_USE),
        "research_only": True,
        "not_trade_signal": True,
    }


def build_equity_factor_catalog() -> dict[str, object]:
    rows = [_row_with_policy(dict(row)) for row in FACTOR_ROWS]
    rows.sort(key=lambda row: str(row["factor_id"]))
    families = sorted({str(row["family"]) for row in rows})
    return {
        "schema_version": SCHEMA_VERSION,
        "report_kind": "equity_factor_catalog",
        "summary": {
            "factor_definition_count": len(rows),
            "factor_family_count": len(families),
            "factor_families": families,
            "operator_summary": (
                "Equity factor definitions are research-only calculation contracts. "
                "They are not executable strategies, not direct trade signals, and not capital-allocation authority."
            ),
        },
        "rows": rows,
        "safety_invariants": {
            "research_only": True,
            "not_trade_signal": True,
            "mutates_registry": False,
            "mutates_frozen_contracts": False,
            "paper_shadow_live_forbidden": True,
            "broker_risk_execution_forbidden": True,
        },
    }


def build_equity_factor_calculation_contracts() -> dict[str, object]:
    rows = []
    for row in FACTOR_ROWS:
        rows.append(
            {
                "factor_id": row["factor_id"],
                "formula_kind": row["formula_kind"],
                "required_fields": list(row["required_fields"]),
                "point_in_time_required": row["point_in_time_required"],
                "restatement_risk": row["restatement_risk"],
                "missing_value_policy": row["missing_value_policy"],
                "lookahead_bias_risk": row["lookahead_bias_risk"],
                "quality_gate_requirements": list(row["quality_gate_requirements"]),
                "allowed_use": list(ALLOWED_USE),
                "forbidden_use": list(FORBIDDEN_USE),
            }
        )
    rows.sort(key=lambda row: str(row["factor_id"]))
    return {
        "schema_version": SCHEMA_VERSION,
        "report_kind": "equity_factor_calculation_contracts",
        "summary": {
            "contract_count": len(rows),
            "operator_summary": (
                "Calculation contracts define required fields and quality gates for research intake only. "
                "Missing fundamental readiness must block factor use."
            ),
        },
        "rows": rows,
        "policy_vocabulary": {
            "allowed_use": list(ALLOWED_USE),
            "forbidden_use": list(FORBIDDEN_USE),
        },
        "safety_invariants": {
            "research_only": True,
            "not_trade_signal": True,
            "mutates_registry": False,
            "mutates_frozen_contracts": False,
            "paper_shadow_live_forbidden": True,
            "broker_risk_execution_forbidden": True,
        },
    }
