"""Compatibility import for QRE diagnostics path contracts.

The canonical read-only path contract lives in
``packages.qre_diagnostics.paths``. This module preserves the original
``research.diagnostics.paths`` import path for existing diagnostics and
dashboard consumers.
"""

from __future__ import annotations

from packages.qre_diagnostics.paths import (
    ACTIVE_COMPONENTS,
    ARTIFACT_HEALTH_PATH,
    CAMPAIGN_EVIDENCE_LEDGER_PATH,
    CAMPAIGN_REGISTRY_PATH,
    DEFAULT_STALE_THRESHOLD_SECONDS,
    DEFERRED_COMPONENTS,
    DIAGNOSTIC_EVIDENCE_STATUSES,
    DIAGNOSTIC_LIMITATION_CODES,
    DIAGNOSTIC_MODES,
    FAILURE_MODES_PATH,
    INPUT_ARTIFACTS,
    MAX_LEDGER_LINES,
    MAX_LEDGER_TAIL_BYTES,
    OBSERVABILITY_DIR,
    OBSERVABILITY_SCHEMA_VERSION,
    OBSERVABILITY_SUMMARY_PATH,
    RESEARCH_DIR,
    SPRINT_PROGRESS_STALE_VS_REGISTRY_SECONDS,
    STALE_THRESHOLD_SECONDS,
    SYSTEM_INTEGRITY_PATH,
    THROUGHPUT_METRICS_PATH,
    stale_threshold_for,
)

__all__ = [
    "ACTIVE_COMPONENTS",
    "ARTIFACT_HEALTH_PATH",
    "CAMPAIGN_EVIDENCE_LEDGER_PATH",
    "CAMPAIGN_REGISTRY_PATH",
    "DEFAULT_STALE_THRESHOLD_SECONDS",
    "DEFERRED_COMPONENTS",
    "DIAGNOSTIC_EVIDENCE_STATUSES",
    "DIAGNOSTIC_LIMITATION_CODES",
    "DIAGNOSTIC_MODES",
    "FAILURE_MODES_PATH",
    "INPUT_ARTIFACTS",
    "MAX_LEDGER_LINES",
    "MAX_LEDGER_TAIL_BYTES",
    "OBSERVABILITY_DIR",
    "OBSERVABILITY_SCHEMA_VERSION",
    "OBSERVABILITY_SUMMARY_PATH",
    "RESEARCH_DIR",
    "SPRINT_PROGRESS_STALE_VS_REGISTRY_SECONDS",
    "STALE_THRESHOLD_SECONDS",
    "SYSTEM_INTEGRITY_PATH",
    "THROUGHPUT_METRICS_PATH",
    "stale_threshold_for",
]
